// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfssrfninhlzcgqdejdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmc3NyZm5pbmhsemNncWRlamRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzNzQ2MTMsImV4cCI6MjA1MTk1MDYxM30.bk9aaeVQF2Trw9F73QC5r6W8dDcfkLJBPFSuHyeBh6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);